package com.piyushsinghal.api.tests;

import com.piyushsinghal.api.base.BaseTest;
import com.piyushsinghal.api.models.Post;
import com.piyushsinghal.api.utils.ApiEndpoints;
import io.qameta.allure.*;
import org.testng.annotations.Test;

import static io.restassured.RestAssured.given;
import static org.testng.Assert.*;

/**
 * Tests for POST /posts endpoint (create operations).
 *
 * Demonstrates:
 *   - POJO-based request serialization (no raw JSON strings)
 *   - Response body assertions
 *   - Status code validation for resource creation
 */
@Epic("Post Management API")
@Feature("Create Posts")
public class CreatePostTest extends BaseTest {

    @Test(description = "POST /posts - should create a new post with valid data")
    @Story("Create post with complete data")
    @Severity(SeverityLevel.BLOCKER)
    public void shouldCreatePostWithValidData() {
        Post newPost = Post.builder()
                .userId(1)
                .title("Test Post by Piyush")
                .body("This is a test post created via REST Assured automation.")
                .build();

        Post created = given()
                .body(newPost)
                .when()
                .post(ApiEndpoints.POSTS)
                .then()
                .statusCode(201)
                .time(lessThanMillis(2000))
                .extract()
                .as(Post.class);

        assertEquals(created.getTitle(), newPost.getTitle(), "Title mismatch");
        assertEquals(created.getBody(), newPost.getBody(), "Body mismatch");
        assertEquals(created.getUserId(), newPost.getUserId(), "UserId mismatch");
        assertNotNull(created.getId(), "ID should be generated by the server");
    }

    @Test(description = "POST /posts - should create post with minimal required fields")
    @Story("Create post with minimal data")
    @Severity(SeverityLevel.NORMAL)
    public void shouldCreatePostWithMinimalData() {
        Post newPost = Post.builder()
                .title("Minimal Post")
                .userId(1)
                .build();

        Post created = given()
                .body(newPost)
                .when()
                .post(ApiEndpoints.POSTS)
                .then()
                .statusCode(201)
                .extract()
                .as(Post.class);

        assertEquals(created.getTitle(), "Minimal Post");
        assertNotNull(created.getId());
    }

    @Test(description = "POST /posts - should handle empty body gracefully")
    @Story("Edge cases")
    @Severity(SeverityLevel.MINOR)
    @Description("JSONPlaceholder accepts empty bodies and returns 201. Real APIs would return 400 here.")
    public void shouldHandleEmptyBodyGracefully() {
        given()
                .body("{}")
                .when()
                .post(ApiEndpoints.POSTS)
                .then()
                .statusCode(201);
    }

    private static org.hamcrest.Matcher<Long> lessThanMillis(long millis) {
        return org.hamcrest.Matchers.lessThan(millis);
    }
}
